# Generated by Django 5.2.7 on 2025-11-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_travel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='travel_style',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_vector', models.JSONField(blank=True, default=list)),
                ('age_vector', models.JSONField(blank=True, default=list)),
                ('style_vector', models.JSONField(blank=True, default=list)),
                ('mbti_vector', models.JSONField(blank=True, default=list)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='travel.userprofile')),
            ],
        ),
    ]
