# Generated by Django 5.2.5 on 2025-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_userprofile_travel_style_useranalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalysis',
            name='season_vector',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
